version: '3'
services:
  server_tcp:
    build: ./tcp/server
    container_name: tcp_server
    ports:
      - "587:587"

  client_tcp:
    build: ./tcp/client
    container_name: tcp_client
    depends_on:
      - server_tcp
    environment:
      - SERVER_HOST=server_tcp
      - IS_DOCKER=true
      - USE_SESSION=${USE_SESSION:-false}  # Variável para usar sessão (definida no momento da execução)
      - WRITE_TO_FILE=${WRITE_TO_FILE:-true}  # Variável para salvar resultados em arquivo
      - PRINT_OUTPUT=${PRINT_OUTPUT:-false}  # Variável para imprimir no terminal
      - OUTPUT_FILENAME=docker_tcp_metrics.csv  # Nome do arquivo de saída
    volumes:
      - ./outputs:/app/outputs

  server_udp:
    build: ./udp/server
    container_name: udp_server
    ports:
      - "25:25"

  client_udp:
    build: ./udp/client
    container_name: udp_client
    depends_on:
      - server_udp
    environment:
      - SERVER_HOST=server_udp
      - IS_DOCKER=true
      - WRITE_TO_FILE=${WRITE_TO_FILE:-true}  # Variável para salvar resultados em arquivo
      - PRINT_OUTPUT=${PRINT_OUTPUT:-false}  # Variável para imprimir no terminal
      - OUTPUT_FILENAME=docker_udp_metrics.csv  # Nome do arquivo de saída
    volumes:
      - ./outputs:/app/outputs
